name: Setup Environment
description: Setup Node.js environment and install dependencies

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc
        cache: npm

    - name: Install dependencies
      run: npm ci
      shell: bash
